//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int register_id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> school_id { get; set; }
        public Nullable<int> telno { get; set; }
    
        public virtual course course { get; set; }
        public virtual school school { get; set; }
    }
}
